"""add idescenario_origen to escenario

Revision ID: 1b83f8218153
Revises: 80e7c5978069
Create Date: 2026-05-09 17:56:52.883242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b83f8218153'
down_revision: Union[str, Sequence[str], None] = '80e7c5978069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('escenario', sa.Column('idescenario_origen', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'escenario', 'escenario', ['idescenario_origen'], ['idescenario'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'escenario', type_='foreignkey')
    op.drop_column('escenario', 'idescenario_origen')
    # ### end Alembic commands ###
